<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>IncidentCommander</RootNamespace>
    <AssemblyName>IncidentCommander</AssemblyName>
  </PropertyGroup>

</Project>
